backend:
  name: github
  repo: FUNPAPI-2002/FUNPAPI-SITE # <-- Deve ficar exatamente assim
  branch: master # ou main, dependendo da sua branch padrão

media_folder: "public/media"
public_folder: "media"


collections:
  - name: "projetos"
    label: "Ações e Projetos"
    folder: "src/content/projetos"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo para o Card", name: "short_description", widget: "text", hint: "Texto curto e direto que vai aparecer na página inicial."}
      - label: "Descrição Completa"
        name: "description"
        widget: "markdown"
        editor_components: ["image", "code-block", "align"]
      - {label: "Imagem Principal (Capa)", name: "image", widget: "image", required: false}
      - {label: "Legenda da Capa", name: "image_caption", widget: "string", required: false}
      - label: "Galeria de Fotos Extras"
        name: "gallery"
        widget: "list"
        required: false
        fields:
          - {label: "Foto", name: "photo", widget: "image"}
          - {label: "Legenda da Foto", name: "caption", widget: "string", required: false}